rules_folder: rules
run_every:
  minutes: 5
buffer_time:
  hours: 4

es_host: ${ES_HOST}
es_port: ${ES_POST}
es_url_prefix: ${ES_URL_PREFIX}
smtp_host: localship

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2
